- netif-forward/config.ml
- netif-forward/unikernel.ml
This network example forwards packets received from the first interface to the second one.
> Add a network example with two interfaces

- block/config.ml
to workaround issue https://github.com/mirage/xen-arm-builder/issues/47, taken from @djs55 fix on http://lists.xenproject.org/archives/html/mirageos-devel/2015-01/msg00112.html.
This might need to be applied to the other examples that use block devices in this repo
> passing "xvda1" to block_of_file for when using xen

- static_website/README.md
- static_website/config.ml
The main change here is to run the static_website example on an unpriviliged port, as previously it required root to run the examples. Prior to this change, if you run the README examples without being root you get the following running `make run`:
```
Manager: connect
Manager: configuring
Manager: socket config currently ignored (TODO)
Fatal error: exception Unix.Unix_error(Unix.EACCES, "bind", "")
Raised at file "src/core/lwt.ml", line 788, characters 22-23
Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Called from file "main.ml", line 85, characters 2-28
make: *** [run] Error 2
```
> Improvements to website example

- block/generate_disk_img.sh
On fish shell, this script doesn't work without a shell being specified. This way it works everywhere.
> Specified shell for script

- .travis.yml
- Makefile
- tracing/config.ml
- tracing/unikernel.ml
This adds a tracing example, based on @talex5's [blog post](https://mirage.io/wiki/profiling).
On top of the documentation value, it also stresses the tracing code for mirage/functoria's CI.
> Add a tracing example.

- README.md
mirage-dev is often home to experimental packages or staging packages,
and since remotes are not switch-specific it is likely bad advice to add
this remote.  It's no longer necessary to add this remote to get mirage 2.0 and hasn't been for some time.
> Remove instructions to add mirage-dev remote to opam.

- block/README.md
- block/config.ml
`mirage` will now generate an example .xl file which contains the path
to the file image, and `xl` will take care of setting up loop devices
if necessary. Previously we had to do this by hand, which meant that
running the Xen example was more complicated than running the Unix example.
Now the unikernel config.ml is independent of whether the target build is
for Xen or Unix.
Fixes #114
Signed-off-by: David Scott <dave.scott@docker.com>
> Fix block example

- README.md
It seems some of the skeletons - at least the static_website one require the functoria based version.
> require mirage 2.7.0

- Makefile
- lwt/Makefile
Signed-off-by: Mindy Preston <mindy.preston@docker.com>
> Run `mirage-configure` with --$MODE rather than -t $MODE.

- .travis.yml
- dns/README.md
- dns/config.ml
- dns/unikernel.ml
- Split the code into smaller functions.
- Use logging API instead of passing a console around.
- Add README.
- Replace network configuration with generic_stackv4 (allows running
with the native stack too).
- Move hard-coded settings to top of file.
- Comment out confusing/unlabelled hexdump.
- Don't send client test from source port that the server is listening
on.
- Listen on port 53 by default. If a non-default port is used,
`nslookup` must be run in interactive mode and in this mode it gets
`SERVFAIL` for some reason.
> Clean up DNS example

- dhcp/config.ml
A KV_RO is no longer used in the DHCP examples, so don't try to make one via `crunch`.
> remove call to `crunch files`

- block/config.ml
- block/unikernel.ml
- conduit_server_manual/config.ml
- conduit_server_manual/unikernel.ml
- console/unikernel.ml
- dhcp/config.ml
- dhcp/unikernel.ml
- ethifv4/config.ml
- ethifv4/unikernel.ml
- hello/config.ml
- hello/unikernel.ml
- http-fetch/config.ml
- http-fetch/unikernel.ml
- io_page/config.ml
- io_page/unikernel.ml
- kv_ro_crunch/config.ml
- kv_ro_crunch/unikernel.ml
- ping/config.ml
- ping/unikernel.ml
- ping6/config.ml
- ping6/unikernel.ml
A number of our examples call `OS.Time`.  `OS` is in scope because we link in one of the libraries of `mirage-platform` and so this compiles, but the dependency on `Time` hasn't been properly stated or exposed when we do this.
Where we call `Time.sleep`, explicitly pass the `time` module to `foreign` and the `default_time` impl to `register` in the configuration file, and take a `Time` module argument in `unikernel.Main` and `_time` argument to `start`.
> replace OS.Time calls with proper functorized Time

- clock/config.ml
- clock/unikernel.ml
- dhcp/config.ml
- dhcp/unikernel.ml
- dns/config.ml
- dns/unikernel.ml
- ethifv4/config.ml
- ethifv4/unikernel.ml
- ping/config.ml
- ping/unikernel.ml
- ping6/config.ml
- ping6/unikernel.ml
- static_website/config.ml
- static_website/dispatch.ml
- static_website_tls/config.ml
- static_website_tls/dispatch.ml
Use PCLOCK and MCLOCK instead of CLOCK.  Also, include a `clock` example which illustrates the difference between these two module types.
> New clock api

- .gitignore
- conduit_server/config.ml
- conduit_server_manual/config.ml
- io_page/config.ml
These changes fix the build with `MODE=ukvm` and `MODE=virtio`.
@yomimono Could you please check I'm doing the right thing in 9073886 and not papering over a dependency problem in the `mirage` frontend for the Solo5 targets. (See also #177)
> Fixes to build against Solo5 targets

- .travis.yml
With #181 and dependencies in place, we can now build mirage-skeleton for the Solo5 targets (ukvm, virtio).
Note that I've added these for both the 4.02 and 4.03 compilers, perhaps that is overkill in terms of needlessly slowing down the build?
> Travis: Add Solo5 (ukvm, virtio) targets

- tracing/unikernel.ml
`conduit_server`, `http-fetch`, `static_website`, and `static_website_tls` also need fixes for this issue, but their fixes will be in `conduit` which wraps the calls to `STACKV4`.
> have tracing example explicitly call STACKV4.listen

- tracing/unikernel.ml
This reverts commit 08308ba01eabca4fec4f98250a12028ce6779da8.  The
change necessitating this one was backed out of mirage-tcpip.
> Revert "have tracing example explicitly call STACKV4.listen"

- dhcp/config.ml
- dhcp/unikernel.ml
I'm actually not particularly convinced that we really need to split on `\n` here... any opinion @yomimono @haesbaert 
The reason to get rid of `Str` is that there are better options in OCaml for regular expressions, and it also adds C code to our OCaml runtime...
please let me know what you think
> use Astring instead of Str in dhcp example

- lwt/Makefile
- ping6/config.ml
- ping6/unikernel.ml
This way, `mirage configure --help` shows the keys for configuring ipv6.
> Use create_ipv6 in ping6 example

- Makefile
- lwt/Makefile
let's see what travis says... tracing example is still likely broken with
```
File "unikernel.ml", line 15, characters 6-17:
Error: This pattern matches values of type [< `Error of 'a | `Ok of 'b ]
but a pattern was expected which matches values of type
(S.TCPV4.flow, S.TCPV4.error) Result.result =
(S.TCPV4.flow, S.TCPV4.error) result
```
> don't repeat command line flags

- Makefile
this helps (at least me) for testing, esp with https://github.com/hannesm/mirage/commit/111d4463398f25fd43d0d5e3e9369b5ec8f68b2c to avoid depext calls (which are pretty expensive)
> copy Makefile.user around; also make clean in the same manner

- .travis.yml
- Makefile
- device-usage/prng/config.ml
- device-usage/prng/unikernel.ml
this is a small example using the provided random number generators ;)
for unix, the `package ~subllibs:["mirage"] "nocrypto"` is needed, since nocrypto.mirage is only in a xen/freestanding world dragged in as dependency.  unix uses nocrypto.lwt (and the rng initialisation over there).
> device-usage/prng: print some random numbers, and the supported entropy sources

- applications/static_website_tls/dispatch.ml
also, silence warning about unused variable `clock` in `start`
> no need to manually set log level and create the mirage logs reporter

- applications/dhcp/unikernel.ml
This was broken on the Clock -> MClock conversion.
Good news is that the library doesn't behave so badly, it was emiting
Leases with duration=0.
Next version of charrua-core should take an Int64 as the argument for time.
18166efdf6b434ecb22bec23a322fa30e57975f2
> Fix dhcp application.

- applications/dhcp/config.ml
- applications/dhcp/unikernel.ml
Will fix tests, once charrua-core 0.5 is released.
> charrua-core expects int32 time now, not float

- .travis.yml
- applications/dns/config.ml
- device-usage/prng/config.ml
@hannesm this is the smallest-possible try to fix the build.
This was about a moved package, `nocrypto`. It moved from `ocaml-freestanding` to `mirage-solo5`.
Our [config.ml for that](https://github.com/mirage/mirage-skeleton/blame/cc3f78e36e77b188b821b5fde3f876b762df7297/device-usage/prng/config.ml#L11)
A [PR elsewhere that does the same change](https://github.com/ocaml/opam-repository/pull/9416/files)
This OCaml version is not supported, right now.
> Build fix: nocrypto moved to mirage-solo5; unsupported Xen on 4.03 dropped from CI matrix; application/dns package updates

- README.md
This PR changes the example output version number to `3.0.5`.
(Currently, the example output version number is the _same_ as the "at least 3.0.0", in the previous sentence.)
> README: Use 3.0.5 in version instruction wording

- README.md
This PR edits the code examples so that their indentation is _the same_ in all of the examples.
> README: Code fences same on all sections

- .travis.yml
- applications/static_website_tls/dispatch.ml
- device-usage/conduit_server/config.ml
- device-usage/http-fetch/config.ml
Related to [mirage/ocaml-cohttp#572]
Signed-off-by: David Scott <dave@recoil.org>
> Rename mirage-http to cohttp-mirage

- .travis.yml
- Makefile
- device-usage/prng/unikernel.ml
Include a test for the `muen` backend, make a few changes so it can pass.  Pin `mirage` since this is not yet released.
> get ready for mirage 3.1.0 release

- .gitignore
- .travis.yml
- README.md
- device-usage/prng/unikernel.ml
As of Solo5 0.4.0, the "ukvm" target has been renamed to "hvt". Update mirage-skeleton to match. Along the way fix some nits in the documentation, and ignore more generated outputs.
CI is not expected to pass here; this needs to be merged concurrently with mirage/mirage#924.
/cc mirage/mirage#923.
> Updates for Solo5 0.4.0

- .travis.yml
the unix testrun will still fail since they assume some tap devices being around which are not (device-usage/ping6 ; device-usage/network)
> cohttp got released, no need for a custom overlay anymore

- device-usage/block/config.ml
Following https://github.com/mirage/mirage/pull/1053
> Update to not use the Type constructor directly

- Makefile
- device-usage/pgx/config.ml
- device-usage/pgx/unikernel.ml
This adds a very small example of a mirage unikernel interacting with a postgresql database using the newly published pgx_lwt_mirage library.
> add small example for postgres (using pgx)

- Makefile
If there is no `Makefile` (because of some partial cleanups), `mirage clean` should always work.
> Fix `make clean`

- Makefile
Currently, copying opam files makes opam monorepo fail because of the duplicate detection feature in 2.0.7.
> Use opam-monorepo's recurse-opam option

- applications/docteur/config.ml
A small fix when GitHub does not allow us to us `git://` protocol anymore.
> Use https:// instead of git:// to build the docteur image

- applications/docteur/config.ml
Spotted by @TheLortex where we generate `docteur-unix` for our unikernel `docteur` which mislead the compilation (because the `docteur-unix` package already exists).
> Rename the docteur example to static_kv_ro

- device-usage/network/config.ml
- device-usage/network/unikernel.ml
- device-usage/tracing/config.ml
- device-usage/tracing/unikernel.ml
for https://github.com/mirage/mirage/pull/1341
the only leftover is "pgx" which library (pgx-mirage) uses a stackv4. it doesn't really look maintained, is anyone using it? I'm happy to propose a PR for pgx if anyone is actually using it.
> use stackv4v6 instead of stackv4

- Makefile
We found an error when we tried to update `mirage-opam-overlays` and it seems that `$(eval ...)` interprets `#` as a comment. When we try to set repositories to a specific commit, the Makefile does not take in account the hash of the commit due to the `#` prefix. This patch wants to solve this issue.
> Protect repositories from the Makefile parser when they contain '#'

- device-usage/block/unikernel.ml
With mirage-block.3.0.1 we now have `Mirage_block.pp_info`.
> Use Mirage_block.pp_info

- Makefile
- device-usage/block/Makefile.user
- device-usage/block/README.md
- device-usage/block/config.ml
- device-usage/block/unikernel.ml
This attempts to simplify the example a bit, and updates to use newer functions from cstruct. A notable change is the disk image is not generated by mirage anymore. The generated image could be overwritten by invocations of `mirage configure` and `mirage build` which is confusing if you are modifying the example. Furthermore, it complicates the example a lot by introducing a "*custom dependency*", dune rules etc., and the `start` function takes another unit parameter due to `~extra_deps` without explanation as to why. In my personal opinion I prefer to keep (modifiable) data out of the build of the unikernel.
Finally, I'm not convinced a test suite is the best example, and I may submit another PR if I get a better idea.
> Update block device usage example

- device-usage/disk-lottery/README.md
- device-usage/disk-lottery/config.ml
- device-usage/disk-lottery/lotto.ml
- device-usage/disk-lottery/lotto.mli
- device-usage/disk-lottery/unikernel.ml
The game is a random "dice" game. A random number is rolled, and the number is compared with the number stored in the game state. If it's higher, you win. The new high score is stored on the block device. Each sector is a slot to store game state in, so multiple games and be played.
I think this example is more interesting than the existing block device example. The existing example does not leverage that the block device is persistent, and would work just as well with an ephemeral in-memory "block device".
> Add game example that uses block devices

- applications/dns/config.ml
- applications/dns/unikernel.ml
- applications/docteur/config.ml
- applications/docteur/unikernel.ml
- applications/git/config.ml
- applications/git/unikernel.ml
- applications/http/config.ml
- applications/http/unikernel.ml
- applications/static_website_tls/config.ml
- applications/static_website_tls/dispatch.ml
- device-usage/http-fetch/config.ml
- device-usage/http-fetch/unikernel.ml
- device-usage/network/config.ml
- device-usage/network/unikernel.ml
- device-usage/prng/unikernel.ml
- tutorial/hello-key/config.ml
- tutorial/hello-key/unikernel.ml
To be tested with https://github.com/mirage/mirage/pull/1442
> Update to latest mirage

- tutorial/hello/config.ml
- tutorial/hello/unikernel.ml
- tutorial/noop/config.ml
- tutorial/noop/unikernel.ml
The noop example can be simplified to a single line: a unikernel with no jobs. This lets us focus on explaining `Mirage.register` and talk a bit about jobs without defining any jobs, and we avoid having to explain functors straight away.
In #360 the time device was removed from the hello example (not sure why). I add it back again as we need *some* device, and we might as well explain it with a device that does something useful. Furhtermore, the named argument `~packages` is moved at the end of the call to `Mirage.main` so we unambiguously can refer to its first and second arguments.
An update to mirage-www is coming within the next few minutes.
> Simplify noop example, revert hello example

- applications/dns/config.ml
- applications/dns/unikernel.ml
- applications/docteur/config.ml
- applications/docteur/unikernel.ml
- applications/git/config.ml
- applications/git/unikernel.ml
- applications/http/config.ml
- applications/http/unikernel.ml
- applications/static_website_tls/config.ml
- applications/static_website_tls/dispatch.ml
- device-usage/http-fetch/config.ml
- device-usage/http-fetch/unikernel.ml
- device-usage/network/config.ml
- device-usage/network/unikernel.ml
- device-usage/prng/unikernel.ml
- tutorial/hello-key/config.ml
- tutorial/hello-key/unikernel.ml
Reverts mirage/mirage-skeleton#364 as it doesn't work with the latest version of mirage. The fix is present on `dev`.
> Revert "Update to latest mirage"

- applications/static_website_tls/config.ml
- device-usage/disk-lottery/config.ml
- device-usage/http-fetch/config.ml
- device-usage/network/config.ml
- device-usage/pgx/config.ml
- tutorial/hello-key/config.ml
> revert the Key.v -> key renaming, which doesn't work with latest release of mirage

- applications/static_website_tls/config.ml
Using non-standard ports 8080 and 4433 are perhaps nice for the Unix target where the standard ports are privileged, but for all other targets they are less desirable.
> applications/static_website_tls: use standard ports

- applications/static_website_tls/dispatch.ml
The [default port](https://en.wikipedia.org/wiki/HTTPS#Difference_from_HTTP) for HTTPS is 443.
> fix default https port

- mirage-skeleton.opam
Openmirage.org seems to not respond. Mirage.io is in a precarious situation with .io, so use mirageos.org.
> Update website in opam file
