mirage/mirage-skeleton

.travis.yml
=> Add mirage-dev extra remote

block/config.ml, block/unikernel.ml, console/config.ml, kv_ro/config.ml, kv_ro_crunch/config.ml, stackv4/config.ml, stackv4/unikernel.ml
specifically, start to resync with `/wiki/hello-world.md`
do not merge yet. 
works in tandem with mirage/mirage-www#370
=> several `config.ml` updates; resync with wiki

static_website/config.ml, static_website/dispatch.ml
Discussion: http://lists.xenproject.org/archives/html/mirageos-devel/2015-05/msg00206.html
=> static_website: set Content-Type using magic-mime.

ethifv4/config.ml, ethifv4/unikernel.ml, ping/config.ml, ping/unikernel.ml
=> Updates to work with mirage/mirage-types/mirage-tcpip 2.6.0

static_website/config.ml
Signed-off-by: David Scott <dave.scott@citrix.com>
=> Support attaching htdocs as a tar-formatted block device

Makefile, dhcp/README.md, dhcp/config.ml, dhcp/files/dhcpd.conf, dhcp/unikernel.ml
This adds the basic code needed for making a dhcp server as discussed in:
http://lists.xenproject.org/archives/html/mirageos-devel/2015-10/msg00039.html
=> Add an example for a dhcp server using charrua-core.

.gitignore, .merlin, Makefile, block/config.ml, conduit_server/config.ml, conduit_server_manual/config.ml, conduit_server_manual/unikernel.ml, dhcp/README.md, dhcp/config.ml, dhcp/files/dhcpd.conf, dhcp/unikernel.ml, dns/config.ml, ethifv4/config.ml, hello/config.ml, hello/unikernel.ml, http-fetch/config.ml, kv_ro/config.ml, lwt/Makefile, netif-forward/config.ml, network/config.ml, ping/config.ml, ping6/config.ml, stackv4/config.ml, static_website/config.ml, static_website_tls/config.ml, tracing/config.ml, tracing/unikernel.ml
=> Functoria version

dhcp/README.md, static_website/README.md
It's no longer *necessary* to edit .xl files to add vifs -- the generated .xl will have a guessed bridge name depending on the bridges visible on the system. Instead, the user might need to tweak the generated `vif` if the guess has gone wrong (hopefully unlikely).
=> Minor README.md updates

static_website_tls/config.ml, static_website_tls/dispatch.ml
taken from https://github.com/Drup/No.
thanks @drup
=> refactor static_website_tls: shortcuts for tls

.travis.yml, Makefile, Makefile.config, network/unikernel.ml, testrun.sh
Test the things we build actually run.
=> run all executables on travis

.travis.yml, dhcp/unikernel.ml
Make DHCP example compile against current charrua-core (0.3).
=> Charrua 0.3

.travis.yml, Makefile
(mainly to look whether travis is happy with the rest)
=> fix builds and make travis happy

Makefile, README.md
Fixes #131, that I've also tapped into...
=> make README sample-* make commands more obvious

dhcp/config.ml, dhcp/unikernel.ml, dns/unikernel.ml, ethifv4/config.ml, ethifv4/unikernel.ml, network/unikernel.ml, stackv4/unikernel.ml
Build against merged and nearly-merged post-2.8.0 changes in mirage, mirage-types, tcpip.
=> Build against shiny new stuff

Makefile, block/config.ml, block/generate_disk_img.sh, block/unikernel.ml
I stole^Wcherry-picked this commit from @Engil (and added the Makefile modifications myself)
=> update block example

Makefile, block/config.ml, block/generate_disk_img.sh, block/unikernel.ml
=> Block mirage dev

Makefile, README.md, block/README.md, dns/README.md, static_website/README.md
Needed for https://github.com/mirage/mirage/issues/461 .
=> changes references to --unix/--xen to -t unix/xen

Makefile, README.md, block/README.md, dns/README.md, lwt/Makefile, static_website/README.md
Cherry-picks commits from mirage-dev, plus improvements from @amirmc (thanks!).
=> Change --unix/--xen to -t unix/xen & update README

.gitignore, app_info/config.ml, app_info/unikernel.ml
This is a very simple example, it dumps the info on the console. 
I can add an example that combines static_website and app_info if people want it, but it's going to be 90% cohttp/conduit boilerplate...
=> Add app_info example. 

block/config.ml, block/unikernel.ml, console/config.ml, console/unikernel.ml, dns/config.ml, dns/unikernel.ml, hello/config.ml, hello/unikernel.ml, http-fetch/config.ml, http-fetch/unikernel.ml, io_page/config.ml, io_page/unikernel.ml, kv_ro/config.ml, kv_ro/unikernel.ml, kv_ro_crunch/config.ml, kv_ro_crunch/unikernel.ml, lwt/src/config.ml, lwt/src/unikernels.ml
@hannesm's sleep-ns branch rebased on top of functorized time.
=> sleep in nanoseconds

dhcp/unikernel.ml, netif-forward/unikernel.ml, ping/unikernel.ml, ping6/unikernel.ml
see https://github.com/mirage/mirage-dev/pull/166
=> fix for network error

ethifv4/config.ml, lwt/src/config.ml
this works well with https://github.com/mirage/mirage/pull/611
=> switch back to default_random, now that mirage has a sensible notion thereof

.gitignore, Makefile, app_info/config.ml, block/config.ml, conduit_server/config.ml, console/config.ml, dhcp/config.ml, dns/config.ml, ethifv4/config.ml, hello/config.ml, http-fetch/config.ml, io_page/config.ml, kv_ro/config.ml, kv_ro_crunch/config.ml, lwt/Makefile, lwt/src/config.ml, netif-forward/config.ml, ping6/config.ml, static_website/config.ml, static_website_tls/config.ml
=> adapt to functoria changes

conduit_server/config.ml, dhcp/config.ml, dns/config.ml, ethifv4/config.ml, http-fetch/config.ml, network/config.ml, ping6/config.ml, stackv4/config.ml, static_website/config.ml, static_website_tls/config.ml, tracing/config.ml
Companion to https://github.com/mirage/mirage/pull/715 .  See passing tests at https://travis-ci.org/yomimono/mirage-dev/builds/180195689 .
=> replace tap0 with default_network

lwt/Makefile
See https://github.com/mirage/functoria/pull/87 for some background.  This seems to work locally, so we'll see what Travis makes of it.
=> don't specify mode twice

tracing/unikernel.ml
=> tracing needs updates for result-y FLOW.write/create

static_website/htdocs/index.html
W3C standards define an Open Web Platform for application development that has the unprecedented potential to enable developers to build rich interactive experiences, powered by vast data stores, that are available on any device.
=> w3c compliance

.travis.yml
Should've preserved this in #216 but didn't, so here it is again.
=> Test maintenance

.travis.yml, applications/static_website_tls/dispatch.ml, device-usage/conduit_server/config.ml, device-usage/http-fetch/config.ml
now that it is merged to opam-repository, I took the freedom to cherry-pick @djs55 commits. thanks!
=> mirage 3.0.7

.travis.yml, Makefile, device-usage/prng/unikernel.ml
that's #257 with some travis.yml tweaks (couldn't figure out how to push to 257). let's see whether travis is happy
=> Muen ready

applications/dns/unikernel.ml, applications/static_website_tls/dispatch.ml, device-usage/kv_ro/unikernel.ml, device-usage/ping6/unikernel.ml
changes needed for mirage 3.5.0 :)
=> Releng 3.5.0

applications/dhcp/config.ml
see https://github.com/mirage/charrua-core/pull/100
=> dhcp server: adapt to charrua naming changes

device-usage/http-fetch/config.ml, device-usage/http-fetch/unikernel.ml
once mirage/mirage#996 is merged and released, this will magically work
=> http-fetch: make uri configurable, don't hardcode resolver

.travis.yml, Makefile
=> add missing unikernels to makefile

.travis.yml, README.md, device-usage/prng/config.ml, device-usage/prng/unikernel.ml, opam
to-be-restarted + merged once https://github.com/ocaml/opam-repository/pull/14983 is through
=> Mirage.3.6.0

device-usage/block/config.ml
Changes required for https://github.com/mirage/mirage/pull/1077
=> Use the new actions API

applications/static_website_tls/dispatch.ml, device-usage/conduit_server/unikernel.ml, device-usage/http-fetch/config.ml, device-usage/http-fetch/unikernel.ml, opam
=> updates for mirage 3.10.2 (conduit 2.3)

applications/static_website_tls/config.ml, device-usage/conduit_server/config.ml, device-usage/http-fetch/config.ml
Sync https://github.com/mirage/mirage-skeleton/pull/301 to mirage-dev branch.
=> Upgrade conduit to use v4v6 stack (sync with master)

applications/dhcp/unikernel.ml, device-usage/block/unikernel.ml, device-usage/network/unikernel.ml, device-usage/pgx/config.ml
Same as #304 but for MirageOS 4.
=> Mirage 4 fix

Makefile
Main PR is https://github.com/mirage/mirage/pull/1327
=> adapt to single opam file workflow

applications/git/config.ml, applications/http/config.ml
https://github.com/mirage/mirage/pull/1376
=> Rename git_happy_eyeballs to mimic_happy_eyeballs

applications/git/config.ml
For https://github.com/mirage/mirage/pull/1412
=> adapt to git 3.13 changes

applications/crypto/config.ml, applications/dhcp/config.ml, applications/git/config.ml, device-usage/prng/config.ml
just a question of taste, and moving https://github.com/mirage/mirage/pull/1434 forward
=> move packages to foreign/main, instead of register

tutorial/app_info/config.ml, tutorial/app_info/unikernel.ml
To test with https://github.com/mirage/mirage/pull/1452
=> Use dune-build-info instead of mirage's app_info device

Makefile, applications/dns/config.ml, applications/dns/key.ml, applications/git/config.ml, applications/git/key.ml, applications/http/config.ml, applications/http/key.ml, device-usage/disk-lottery/config.ml, device-usage/disk-lottery/unikernel.ml
To be tested with https://github.com/mirage/mirage/pull/1455
=> Move runtime keys to runtime modules

applications/dns/config.ml, applications/dns/unikernel.ml, applications/docteur/unikernel.ml, applications/git/config.ml, applications/git/unikernel.ml, applications/http/config.ml, applications/http/unikernel.ml, applications/static_website_tls/dispatch.ml, device-usage/disk-lottery/unikernel.ml, device-usage/http-fetch/unikernel.ml, device-usage/network/unikernel.ml, tutorial/hello-key/unikernel.ml
To be tested with https://github.com/mirage/mirage/pull/1501
=> Rename Mirage_key to Mirage_arg

applications/git/config.ml, applications/http/config.ml
To be tested with https://github.com/mirage/mirage/pull/1504
=> Adapt to API changes for Device.connect

applications/crypto/config.ml, applications/dns/config.ml, applications/docteur/config.ml, applications/git/config.ml, applications/http/config.ml, device-usage/littlefs/config.ml, device-usage/ping6/config.ml
To be tested with https://github.com/mirage/mirage/pull/1505
=> Use `main` instead of `foreign`

applications/dhcp/unikernel.ml
see https://github.com/mirage/mirage/pull/1524 that discovered this
=> dhcp: handle return value from N.listen

applications/crypto/config.ml, applications/dhcp/config.ml, applications/dns/config.ml, applications/dns/unikernel.ml, applications/git/config.ml, applications/git/unikernel.ml, applications/http/config.ml, applications/static_website_tls/config.ml, device-usage/block/config.ml, device-usage/clock/config.ml, device-usage/conduit_server/config.ml, device-usage/disk-lottery/config.ml, device-usage/http-fetch/config.ml, device-usage/kv_ro/config.ml, device-usage/network/config.ml, device-usage/pgx/config.ml, device-usage/ping6/config.ml, tutorial/app_info/config.ml, tutorial/hello-key/config.ml, tutorial/hello/config.ml, tutorial/lwt/echo_server/config.ml, tutorial/lwt/heads1/config.ml, tutorial/lwt/heads2/config.ml, tutorial/lwt/timeout1/config.ml, tutorial/lwt/timeout2/config.ml, tutorial/noop/config.ml
for https://github.com/mirage/mirage/pull/1577
=> adjust unikernels

README.md, applications/dns/config.ml, applications/dns/unikernel.ml, applications/git/config.ml, applications/git/unikernel.ml, applications/http/config.ml, applications/http/unikernel.ml, applications/static_website_tls/config.ml, applications/static_website_tls/dispatch.ml, device-usage/disk-lottery/config.ml, device-usage/disk-lottery/unikernel.ml, device-usage/http-fetch/config.ml, device-usage/http-fetch/unikernel.ml, device-usage/network/config.ml, device-usage/network/unikernel.ml, tutorial/hello-key/config.ml, tutorial/hello-key/unikernel.ml
cc @reynir @palainp referencing https://github.com/mirage/mirage/issues/1572
=> move runtime arguments out of config.ml

tutorial/local-library/config.ml, tutorial/local-library/hello/dune, tutorial/local-library/hello/hello.ml, tutorial/local-library/unikernel.ml
This adds a test case for https://github.com/mirage/mirage/pull/1609
=> Add an example that uses ~local_libs
